steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${REPO_NAME}:${BRANCH_NAME}', '.']
  timeout: 2400s
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/${REPO_NAME}:${BRANCH_NAME}']
images:
- gcr.io/${PROJECT_ID}/${REPO_NAME}
timeout: 2400s
